disallowed-methods = [
  { path = "std::env::current_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::canonicalize", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::is_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::is_file", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::is_symlink", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::read_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::read_link", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::symlink_metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::try_exists", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::exists", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::canonicalize", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::is_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::is_file", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::is_symlink", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::read_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::read_link", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::symlink_metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::path::PathBuf::try_exists", reason = "System operations should be done using Sys trait" },
  { path = "std::env::set_current_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::env::split_paths", reason = "System operations should be done using Sys trait" },
  { path = "std::env::temp_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::env::var", reason = "System operations should be done using Sys trait" },
  { path = "std::env::var_os", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::canonicalize", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::copy", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::create_dir_all", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::create_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::DirBuilder::new", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::hard_link", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::OpenOptions::new", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::read_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::read_link", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::read_to_string", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::read", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::remove_dir_all", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::remove_dir", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::remove_file", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::rename", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::set_permissions", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::symlink_metadata", reason = "System operations should be done using Sys trait" },
  { path = "std::fs::write", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::canonicalize", reason = "System operations should be done using Sys trait" },
  { path = "std::path::Path::exists", reason = "System operations should be done using Sys trait" },
]
