// Bindings generated by `windows-bindgen` 0.62.1

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("kernel32.dll" "system" fn GetBinaryTypeW(lpapplicationname : PCWSTR, lpbinarytype : *mut u32) -> BOOL);
windows_link::link!("kernel32.dll" "system" fn GetLastError() -> WIN32_ERROR);
pub type BOOL = i32;
pub type PCWSTR = *const u16;
pub type WIN32_ERROR = u32;
